export const actionTypes = {
  IS_API_LOADING: "IS_API_LOADING",
  API_DATA: "API_DATA",
  API_ERROR: "API_ERROR",
}

export const actionConstants = {
  CURRENTLNG: "CURRENTLNG",
  API_DATA_OF_COVID_COUNTRIES:'API_DATA_OF_COVID_COUNTRIES',
  IS_API_LOADING_FOR_COVID_COUNTRIES:'IS_API_LOADING_FOR_COVID_COUNTRIES',
  IS_API_ERROR_FOR_COVID_COUNTRIES:'IS_API_ERROR_FOR_COVID_COUNTRIES',
  IS_API_ERROR_FOR_GLOBE_INFO:'IS_API_ERROR_FOR_GLOBE_INFO',
}
